### ISSUE TITLE
Place script reference in head section with defer attribute?

### ISSUE THREAD

**Issue by joostf** [Tristandemuijnck/fix-the-flow-interactive-website#1]
https://github.com/Tristandemuijnck/fix-the-flow-interactive-website/blob/1e909455f1b674321f861ee29b476e620256d33f/index.html#L195

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer

**Comment by Tristandemuijnck** [comment]
script defer toegevoegd aan head en script onderaan page verwijderd.

![image](https://user-images.githubusercontent.com/43402897/206690920-5599a83a-58bd-4de7-a8f2-13094138f6a7.png)
