### ISSUE TITLE
Reconsider the binding types you use when

### ISSUE THREAD

**Issue by joostf** [Tristandemuijnck/fix-the-flow-interactive-website#2]
https://github.com/Tristandemuijnck/fix-the-flow-interactive-website/blob/956f01080edd32f9502e16322dd33368d1db063e/scripts/script.js#L1-L17

https://www.developer.com/languages/javascript/javascript-var-let-const-variable-declaration/

**Comment by Tristandemuijnck** [comment]
Ik heb var veranderd naar const, omdat het een value betreft die niet veranderd.

![image](https://user-images.githubusercontent.com/43402897/206692130-ded87f68-4e16-438e-ad1b-4ab3dc148aee.png)

**Comment by joostf** [comment]
Nice!

en waarom zou je op regels 2 en 3 **let** gebruiken?

**Comment by Tristandemuijnck** [comment]
> en waarom zou je op regels 2 en 3 **let** gebruiken?

Ook aangepast naar const, over het hoofd gezien :)

Heb daarnaast ook nog een paar andere let's veranderd naar const, omdat het variabele betreft die niet veranderen.

![image](https://user-images.githubusercontent.com/43402897/206746409-6eb19811-6527-4133-b219-13807bbde000.png)
