### ISSUE TITLE
Name all things in English?

### ISSUE THREAD

**Issue by joostf** [Tristandemuijnck/fix-the-flow-interactive-website#3]
https://github.com/Tristandemuijnck/fix-the-flow-interactive-website/blob/e33c81541e6f28c3dee7d8ff358cf0572a4f9ead/scripts/script.js#L10-L13

It's a convention!

**Comment by Tristandemuijnck** [comment]
Opgelost samen met DRY maken code.
Verder ook nog een aantal variable names aangepast naar Engels.
 
![image](https://user-images.githubusercontent.com/43402897/208185209-9b23f4e4-ad26-401a-be0c-cae5235cecb4.png)
