### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by joostf** [Tristandemuijnck/fix-the-flow-interactive-website#4]
https://github.com/Tristandemuijnck/fix-the-flow-interactive-website/blob/e33c81541e6f28c3dee7d8ff358cf0572a4f9ead/scripts/script.js#L21-L76

Don't repeat code unnecessary. Fix this with a function with parameters

**Comment by Tristandemuijnck** [comment]
Ik heb met een aantal iteraties mijn code geprobeerd te abstraheren. 

Waar het eerst ~90 lines code waren, zijn dit er nu nog maar ~24

![image](https://user-images.githubusercontent.com/43402897/206818416-d50d2b2d-e9a3-48de-9a39-55602c48f815.png)
