### ISSUE TITLE
Use a list in sitew ide navigation

### ISSUE THREAD

**Issue by joostf** [Tristandemuijnck/fix-the-flow-interactive-website#6]
https://github.com/Tristandemuijnck/fix-the-flow-interactive-website/blob/b7fd8c09b29945a6a7ff81e486f330e47972a83e/index.html#L22-L25

http://html5doctor.com/nav-element/

**Comment by Tristandemuijnck** [comment]
Added ul and li

![image](https://user-images.githubusercontent.com/43402897/208204313-ffaab871-d06e-4c1a-811a-abdf17ebee35.png)
