### ISSUE TITLE
Use descriptive name

### ISSUE THREAD

**Issue by joostf** [Tristandemuijnck/fix-the-flow-interactive-website#7]
https://github.com/Tristandemuijnck/fix-the-flow-interactive-website/blob/b7fd8c09b29945a6a7ff81e486f330e47972a83e/scripts/script.js#L28

.. describing the action, e.g. 'highlight' instead of 'countColor'

**Comment by Tristandemuijnck** [comment]
Changed to highlightColor

![image](https://user-images.githubusercontent.com/43402897/208200004-2720d6b6-6c3e-4ccd-9644-ad5b353e1145.png)
