### ISSUE TITLE
Don't animate font-size?

### ISSUE THREAD

**Issue by joostf** [Tristandemuijnck/fix-the-flow-interactive-website#8]
https://github.com/Tristandemuijnck/fix-the-flow-interactive-website/blob/b7fd8c09b29945a6a7ff81e486f330e47972a83e/styles/style.css#L400

It makes the interface jumpy. Use a 'transition: scale(...)'? It doesn't doesn't trigger repaints and thus doesn't effect the flow of the document

**Comment by Tristandemuijnck** [comment]
Fixed, added inline-block onto the span element to be able to add a transform.

![image](https://user-images.githubusercontent.com/43402897/208201637-4e8617d4-8a0f-495c-8ae9-4ddf12fd319a.png)
